name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ndoornekamp/github-pages-blog-action@17861282b0019d8a80bf6a2891b348641fadebfe
        with:
          branch: gh-pages # Optional branch for GitHub Pages