name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ndoornekamp/github-pages-blog-action@cc498917ca3c1e531cce6ed5267c32286c770aac
        with:
          branch: gh-pages # Optional branch for GitHub Pages
