name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ndoornekamp/github-pages-blog-action@ea1018c5bb5734e7acdb6b2adff5c99cd0b391a7
        with:
          branch: gh-pages # Optional branch for GitHub Pages