name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ndoornekamp/github-pages-blog-action@3ed256ec6fbdf2bab5b39825317eea5090b91755
        with:
          branch: gh-pages # Optional branch for GitHub Pages