name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ndoornekamp/github-pages-blog-action@18519017b6886aa9b1335b556a19e85433c1a806
        with:
          branch: gh-pages # Optional branch for GitHub Pages