name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ndoornekamp/github-pages-blog-action@108a2a229422a3e11b8bc9cca4c2b759ff7fe03b
        with:
          branch: gh-pages # Optional branch for GitHub Pages