name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ndoornekamp/github-pages-blog-action@120136a9e4a46fe36a356efa80bebb0966c87f00
        with:
          branch: gh-pages # Optional branch for GitHub Pages