name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ndoornekamp/github-pages-blog-action@c01c54c84b806995d9cb7297247618ce5afa5c8c
        with:
          branch: gh-pages # Optional branch for GitHub Pages