name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ndoornekamp/github-pages-blog-action@c14b46ae5c740028244269869cfb17815857c421
        with:
          branch: gh-pages # Optional branch for GitHub Pages