name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ndoornekamp/github-pages-blog-action@7333b1eb1abbeb6ca013865857d4dcd44d0e031a
        with:
          branch: gh-pages # Optional branch for GitHub Pages