name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ndoornekamp/github-pages-blog-action@f540a60a3d7d313af175192ed07ac803086872ef
        with:
          branch: gh-pages # Optional branch for GitHub Pages