name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ndoornekamp/github-pages-blog-action@07c629653f6ec479c37a400b03298fd94ae29288
        with:
          branch: gh-pages # Optional branch for GitHub Pages