name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ndoornekamp/github-pages-blog-action@bc3389e514b447dd4c53d3617331ae3aa5bfc02a
        with:
          branch: gh-pages # Optional branch for GitHub Pages