name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ndoornekamp/github-pages-blog-action@5e7bbd0b9b99433a47d5d7cfd2c29194c36ac03d
        with:
          branch: gh-pages # Optional branch for GitHub Pages
