name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ndoornekamp/github-pages-blog-action@fa4060c6711400f7771a0834a1b67e8fde3092e2
        with:
          branch: gh-pages # Optional branch for GitHub Pages